In [2]:
import requests
import json
from config import api_key_census
import census
from census import Census
import pandas as pd
import matplotlib.pyplot as plt
import us
from us import states
from scipy.stats import linregress
from scipy import stats

In [4]:
#### API request and save raw data to csv
### API calls for House Value and Monthly Housing cost 2017 to 2011

# Median house value and monthly cost for year 2017
c_value_cost_2017 = Census(api_key_census, year=2017)
census_value_cost_2017 = c_value_cost_2017.acs5.get(("NAME","B25001_001E","B25077_001E","B25105_001E","B25076_001E","B25078_001E"),
                                                    {'for': 'zip code tabulation area:77001,77002,77003,77004,77005,77006,77007,77008,77009,77010,77011,77012,77013,77014,77015,77016,77017,77018,77019,77020,77021,77022,77023,77024,77025,77026,77027,77028,77029,77030,77031,77032,77033,77034,77035,77036,77037,77038,77039,77040,77041,77042,77043,77044,77045,77046,77047,77048,77049,77050,77051,77052,77054,77055,77056,77057,77058,77059,77060,77061,77062,77063,77064,77065,77066,77067,77068,77069,77070,77071,77072,77073,77074,77075,77076,77077,77078,77079,77080,77081,77082,77083,77084,77085,77086,77087,77088,77089,77090,77091,77092,77093,77094,77095,77096,77097,77098,77099,77201,77202,77203,77205,77206,77207,77208,77210,77212,77213,77215,77217,77218,77219,77220,77221,77222,77223,77224,77225,77226,77227,77228,77229,77230,77231,77233,77234,77235,77236,77237,77238,77240,77241,77242,77243,77244,77245,77248,77249,77251,77252,77253,77254,77255,77256,77257,77258,77259,77261,77262,77263,77265,77266,77267,77268,77269,77270,77271,77272,77273,77274,77275,77277,77279,77280,77281,77282,77284,77287,77288,77289,77290,77291,77292,77293,77315,77325,77336,77337,77338,77339,77345,77346,77347,77373,77375,77377,77379,77383,77388,77389,77391,77396,77401,77402,77410,77411,77413,77429,77433,77447,77449,77450,77484,77491,77492,77493,77501,77502,77503,77504,77505,77506,77507,77508,77520,77521,77522,77530,77532,77536,77547,77562,77571,77572,77586,77587,77598'})
census_value_cost_2017 = pd.DataFrame(census_value_cost_2017)
census_value_cost_2017 = census_value_cost_2017.rename(columns={"B25077_001E": "Median Value",
                                                                "B25001_001E": "Total Housing Unit",
                                                                "B25076_001E": "Lower value quartile (dollars)",
                                                                "B25105_001E": "Median monthly housing costs",
                                                                "B25078_001E": "Upper value quartile (dollars)",
                                                                        "NAME": "Name", "zip code tabulation area": "Zipcode"})
census_value_cost_2017 = census_value_cost_2017[["Zipcode",
                                                 "Total Housing Unit",
                                                 "Median Value",
                                                "Lower value quartile (dollars)",
                                                "Upper value quartile (dollars)",
                                                "Median monthly housing costs"]]
# Median house value and monthly cost for year 2016
c_value_cost_2016 = Census(api_key_census, year=2016)
census_value_cost_2016 = c_value_cost_2016.acs5.get(("NAME","B25001_001E","B25077_001E","B25105_001E","B25076_001E","B25078_001E"),
                                                    {'for': 'zip code tabulation area:77001,77002,77003,77004,77005,77006,77007,77008,77009,77010,77011,77012,77013,77014,77015,77016,77017,77018,77019,77020,77021,77022,77023,77024,77025,77026,77027,77028,77029,77030,77031,77032,77033,77034,77035,77036,77037,77038,77039,77040,77041,77042,77043,77044,77045,77046,77047,77048,77049,77050,77051,77052,77054,77055,77056,77057,77058,77059,77060,77061,77062,77063,77064,77065,77066,77067,77068,77069,77070,77071,77072,77073,77074,77075,77076,77077,77078,77079,77080,77081,77082,77083,77084,77085,77086,77087,77088,77089,77090,77091,77092,77093,77094,77095,77096,77097,77098,77099,77201,77202,77203,77205,77206,77207,77208,77210,77212,77213,77215,77217,77218,77219,77220,77221,77222,77223,77224,77225,77226,77227,77228,77229,77230,77231,77233,77234,77235,77236,77237,77238,77240,77241,77242,77243,77244,77245,77248,77249,77251,77252,77253,77254,77255,77256,77257,77258,77259,77261,77262,77263,77265,77266,77267,77268,77269,77270,77271,77272,77273,77274,77275,77277,77279,77280,77281,77282,77284,77287,77288,77289,77290,77291,77292,77293,77315,77325,77336,77337,77338,77339,77345,77346,77347,77373,77375,77377,77379,77383,77388,77389,77391,77396,77401,77402,77410,77411,77413,77429,77433,77447,77449,77450,77484,77491,77492,77493,77501,77502,77503,77504,77505,77506,77507,77508,77520,77521,77522,77530,77532,77536,77547,77562,77571,77572,77586,77587,77598'})
census_value_cost_2016 = pd.DataFrame(census_value_cost_2016)
census_value_cost_2016 = census_value_cost_2016.rename(columns={"B25077_001E": "Median Value",
                                                                "B25001_001E": "Total Housing Unit",
                                                                "B25076_001E": "Lower value quartile (dollars)",
                                                                "B25105_001E": "Median monthly housing costs",
                                                                "B25078_001E": "Upper value quartile (dollars)",
                                                                        "NAME": "Name", "zip code tabulation area": "Zipcode"})
census_value_cost_2016 = census_value_cost_2016[["Zipcode",
                                                 "Total Housing Unit",
                                                 "Median Value",
                                                "Lower value quartile (dollars)",
                                                "Upper value quartile (dollars)",
                                                "Median monthly housing costs"]]
# Median house value and monthly cost for year 2015
c_value_cost_2015 = Census(api_key_census, year=2015)
census_value_cost_2015 = c_value_cost_2015.acs5.get(("NAME","B25001_001E","B25077_001E","B25105_001E","B25076_001E","B25078_001E"),
                                                    {'for': 'zip code tabulation area:77001,77002,77003,77004,77005,77006,77007,77008,77009,77010,77011,77012,77013,77014,77015,77016,77017,77018,77019,77020,77021,77022,77023,77024,77025,77026,77027,77028,77029,77030,77031,77032,77033,77034,77035,77036,77037,77038,77039,77040,77041,77042,77043,77044,77045,77046,77047,77048,77049,77050,77051,77052,77054,77055,77056,77057,77058,77059,77060,77061,77062,77063,77064,77065,77066,77067,77068,77069,77070,77071,77072,77073,77074,77075,77076,77077,77078,77079,77080,77081,77082,77083,77084,77085,77086,77087,77088,77089,77090,77091,77092,77093,77094,77095,77096,77097,77098,77099,77201,77202,77203,77205,77206,77207,77208,77210,77212,77213,77215,77217,77218,77219,77220,77221,77222,77223,77224,77225,77226,77227,77228,77229,77230,77231,77233,77234,77235,77236,77237,77238,77240,77241,77242,77243,77244,77245,77248,77249,77251,77252,77253,77254,77255,77256,77257,77258,77259,77261,77262,77263,77265,77266,77267,77268,77269,77270,77271,77272,77273,77274,77275,77277,77279,77280,77281,77282,77284,77287,77288,77289,77290,77291,77292,77293,77315,77325,77336,77337,77338,77339,77345,77346,77347,77373,77375,77377,77379,77383,77388,77389,77391,77396,77401,77402,77410,77411,77413,77429,77433,77447,77449,77450,77484,77491,77492,77493,77501,77502,77503,77504,77505,77506,77507,77508,77520,77521,77522,77530,77532,77536,77547,77562,77571,77572,77586,77587,77598'})
census_value_cost_2015 = pd.DataFrame(census_value_cost_2015)
census_value_cost_2015 = census_value_cost_2015.rename(columns={"B25077_001E": "Median Value",
                                                                "B25001_001E": "Total Housing Unit",
                                                                "B25076_001E": "Lower value quartile (dollars)",
                                                                "B25105_001E": "Median monthly housing costs",
                                                                "B25078_001E": "Upper value quartile (dollars)",
                                                                        "NAME": "Name", "zip code tabulation area": "Zipcode"})
census_value_cost_2015 = census_value_cost_2015[["Zipcode",
                                                 "Total Housing Unit",
                                                 "Median Value",
                                                "Lower value quartile (dollars)",
                                                "Upper value quartile (dollars)",
                                                "Median monthly housing costs"]]
# Median house value and monthly cost for year 2014
c_value_cost_2014 = Census(api_key_census, year=2014)
census_value_cost_2014 = c_value_cost_2014.acs5.get(("NAME","B25001_001E","B25077_001E","B25105_001E","B25076_001E","B25078_001E"),
                                                    {'for': 'zip code tabulation area:77001,77002,77003,77004,77005,77006,77007,77008,77009,77010,77011,77012,77013,77014,77015,77016,77017,77018,77019,77020,77021,77022,77023,77024,77025,77026,77027,77028,77029,77030,77031,77032,77033,77034,77035,77036,77037,77038,77039,77040,77041,77042,77043,77044,77045,77046,77047,77048,77049,77050,77051,77052,77054,77055,77056,77057,77058,77059,77060,77061,77062,77063,77064,77065,77066,77067,77068,77069,77070,77071,77072,77073,77074,77075,77076,77077,77078,77079,77080,77081,77082,77083,77084,77085,77086,77087,77088,77089,77090,77091,77092,77093,77094,77095,77096,77097,77098,77099,77201,77202,77203,77205,77206,77207,77208,77210,77212,77213,77215,77217,77218,77219,77220,77221,77222,77223,77224,77225,77226,77227,77228,77229,77230,77231,77233,77234,77235,77236,77237,77238,77240,77241,77242,77243,77244,77245,77248,77249,77251,77252,77253,77254,77255,77256,77257,77258,77259,77261,77262,77263,77265,77266,77267,77268,77269,77270,77271,77272,77273,77274,77275,77277,77279,77280,77281,77282,77284,77287,77288,77289,77290,77291,77292,77293,77315,77325,77336,77337,77338,77339,77345,77346,77347,77373,77375,77377,77379,77383,77388,77389,77391,77396,77401,77402,77410,77411,77413,77429,77433,77447,77449,77450,77484,77491,77492,77493,77501,77502,77503,77504,77505,77506,77507,77508,77520,77521,77522,77530,77532,77536,77547,77562,77571,77572,77586,77587,77598'})
census_value_cost_2014 = pd.DataFrame(census_value_cost_2014)
census_value_cost_2014 = census_value_cost_2014.rename(columns={"B25077_001E": "Median Value",
                                                                "B25001_001E": "Total Housing Unit",
                                                                "B25076_001E": "Lower value quartile (dollars)",
                                                                "B25105_001E": "Median monthly housing costs",
                                                                "B25078_001E": "Upper value quartile (dollars)",
                                                                        "NAME": "Name", "zip code tabulation area": "Zipcode"})
census_value_cost_2014 = census_value_cost_2014[["Zipcode",
                                                 "Total Housing Unit",
                                                 "Median Value",
                                                "Lower value quartile (dollars)",
                                                "Upper value quartile (dollars)",
                                                "Median monthly housing costs"]]
# Median house value and monthly cost for year 2013
c_value_cost_2013 = Census(api_key_census, year=2013)
census_value_cost_2013 = c_value_cost_2013.acs5.get(("NAME","B25001_001E","B25077_001E","B25105_001E","B25076_001E","B25078_001E"),
                                                    {'for': 'zip code tabulation area:77001,77002,77003,77004,77005,77006,77007,77008,77009,77010,77011,77012,77013,77014,77015,77016,77017,77018,77019,77020,77021,77022,77023,77024,77025,77026,77027,77028,77029,77030,77031,77032,77033,77034,77035,77036,77037,77038,77039,77040,77041,77042,77043,77044,77045,77046,77047,77048,77049,77050,77051,77052,77054,77055,77056,77057,77058,77059,77060,77061,77062,77063,77064,77065,77066,77067,77068,77069,77070,77071,77072,77073,77074,77075,77076,77077,77078,77079,77080,77081,77082,77083,77084,77085,77086,77087,77088,77089,77090,77091,77092,77093,77094,77095,77096,77097,77098,77099,77201,77202,77203,77205,77206,77207,77208,77210,77212,77213,77215,77217,77218,77219,77220,77221,77222,77223,77224,77225,77226,77227,77228,77229,77230,77231,77233,77234,77235,77236,77237,77238,77240,77241,77242,77243,77244,77245,77248,77249,77251,77252,77253,77254,77255,77256,77257,77258,77259,77261,77262,77263,77265,77266,77267,77268,77269,77270,77271,77272,77273,77274,77275,77277,77279,77280,77281,77282,77284,77287,77288,77289,77290,77291,77292,77293,77315,77325,77336,77337,77338,77339,77345,77346,77347,77373,77375,77377,77379,77383,77388,77389,77391,77396,77401,77402,77410,77411,77413,77429,77433,77447,77449,77450,77484,77491,77492,77493,77501,77502,77503,77504,77505,77506,77507,77508,77520,77521,77522,77530,77532,77536,77547,77562,77571,77572,77586,77587,77598'})
census_value_cost_2013 = pd.DataFrame(census_value_cost_2013)
census_value_cost_2013 = census_value_cost_2013.rename(columns={"B25077_001E": "Median Value",
                                                                "B25001_001E": "Total Housing Unit",
                                                                "B25076_001E": "Lower value quartile (dollars)",
                                                                "B25105_001E": "Median monthly housing costs",
                                                                "B25078_001E": "Upper value quartile (dollars)",
                                                                        "NAME": "Name", "zip code tabulation area": "Zipcode"})
census_value_cost_2013 = census_value_cost_2013[["Zipcode",
                                                 "Total Housing Unit",
                                                 "Median Value",
                                                "Lower value quartile (dollars)",
                                                "Upper value quartile (dollars)",
                                                "Median monthly housing costs"]]
# Median house value and monthly cost for year 2012
c_value_cost_2012 = Census(api_key_census, year=2012)
census_value_cost_2012 = c_value_cost_2012.acs5.get(("NAME","B25001_001E","B25077_001E","B25105_001E","B25076_001E","B25078_001E"),
                                                    {'for': 'zip code tabulation area:77001,77002,77003,77004,77005,77006,77007,77008,77009,77010,77011,77012,77013,77014,77015,77016,77017,77018,77019,77020,77021,77022,77023,77024,77025,77026,77027,77028,77029,77030,77031,77032,77033,77034,77035,77036,77037,77038,77039,77040,77041,77042,77043,77044,77045,77046,77047,77048,77049,77050,77051,77052,77054,77055,77056,77057,77058,77059,77060,77061,77062,77063,77064,77065,77066,77067,77068,77069,77070,77071,77072,77073,77074,77075,77076,77077,77078,77079,77080,77081,77082,77083,77084,77085,77086,77087,77088,77089,77090,77091,77092,77093,77094,77095,77096,77097,77098,77099,77201,77202,77203,77205,77206,77207,77208,77210,77212,77213,77215,77217,77218,77219,77220,77221,77222,77223,77224,77225,77226,77227,77228,77229,77230,77231,77233,77234,77235,77236,77237,77238,77240,77241,77242,77243,77244,77245,77248,77249,77251,77252,77253,77254,77255,77256,77257,77258,77259,77261,77262,77263,77265,77266,77267,77268,77269,77270,77271,77272,77273,77274,77275,77277,77279,77280,77281,77282,77284,77287,77288,77289,77290,77291,77292,77293,77315,77325,77336,77337,77338,77339,77345,77346,77347,77373,77375,77377,77379,77383,77388,77389,77391,77396,77401,77402,77410,77411,77413,77429,77433,77447,77449,77450,77484,77491,77492,77493,77501,77502,77503,77504,77505,77506,77507,77508,77520,77521,77522,77530,77532,77536,77547,77562,77571,77572,77586,77587,77598'})
census_value_cost_2012 = pd.DataFrame(census_value_cost_2012)
census_value_cost_2012 = census_value_cost_2012.rename(columns={"B25077_001E": "Median Value",
                                                                "B25001_001E": "Total Housing Unit",
                                                                "B25076_001E": "Lower value quartile (dollars)",
                                                                "B25105_001E": "Median monthly housing costs",
                                                                "B25078_001E": "Upper value quartile (dollars)",
                                                                        "NAME": "Name", "zip code tabulation area": "Zipcode"})
census_value_cost_2012 = census_value_cost_2012[["Zipcode",
                                                 "Total Housing Unit",
                                                 "Median Value",
                                                "Lower value quartile (dollars)",
                                                "Upper value quartile (dollars)",
                                                "Median monthly housing costs"]]
# Median house value and monthly cost for year 2011
c_value_cost_2011 = Census(api_key_census, year=2011)
census_value_cost_2011 = c_value_cost_2011.acs5.get(("NAME","B25001_001E","B25077_001E","B25105_001E","B25076_001E","B25078_001E"),
                                                    {'for': 'zip code tabulation area:77001,77002,77003,77004,77005,77006,77007,77008,77009,77010,77011,77012,77013,77014,77015,77016,77017,77018,77019,77020,77021,77022,77023,77024,77025,77026,77027,77028,77029,77030,77031,77032,77033,77034,77035,77036,77037,77038,77039,77040,77041,77042,77043,77044,77045,77046,77047,77048,77049,77050,77051,77052,77054,77055,77056,77057,77058,77059,77060,77061,77062,77063,77064,77065,77066,77067,77068,77069,77070,77071,77072,77073,77074,77075,77076,77077,77078,77079,77080,77081,77082,77083,77084,77085,77086,77087,77088,77089,77090,77091,77092,77093,77094,77095,77096,77097,77098,77099,77201,77202,77203,77205,77206,77207,77208,77210,77212,77213,77215,77217,77218,77219,77220,77221,77222,77223,77224,77225,77226,77227,77228,77229,77230,77231,77233,77234,77235,77236,77237,77238,77240,77241,77242,77243,77244,77245,77248,77249,77251,77252,77253,77254,77255,77256,77257,77258,77259,77261,77262,77263,77265,77266,77267,77268,77269,77270,77271,77272,77273,77274,77275,77277,77279,77280,77281,77282,77284,77287,77288,77289,77290,77291,77292,77293,77315,77325,77336,77337,77338,77339,77345,77346,77347,77373,77375,77377,77379,77383,77388,77389,77391,77396,77401,77402,77410,77411,77413,77429,77433,77447,77449,77450,77484,77491,77492,77493,77501,77502,77503,77504,77505,77506,77507,77508,77520,77521,77522,77530,77532,77536,77547,77562,77571,77572,77586,77587,77598'})
census_value_cost_2011 = pd.DataFrame(census_value_cost_2011)
census_value_cost_2011 = census_value_cost_2011.rename(columns={"B25077_001E": "Median Value",
                                                                "B25001_001E": "Total Housing Unit",
                                                                "B25076_001E": "Lower value quartile (dollars)",
                                                                "B25105_001E": "Median monthly housing costs",
                                                                "B25078_001E": "Upper value quartile (dollars)",
                                                                        "NAME": "Name", "zip code tabulation area": "Zipcode"})
census_value_cost_2011 = census_value_cost_2011[["Zipcode",
                                                 "Total Housing Unit",
                                                 "Median Value",
                                                "Lower value quartile (dollars)",
                                                "Upper value quartile (dollars)",
                                                "Median monthly housing costs"]]

In [5]:
#### API request and save raw data to csv
# Total employment in civil workforce and Total time travel to work for year 2017

census_work_2017 = c_value_cost_2017.acs5.get(("NAME","B23025_004E","B08135_001E"),
                                                    {'for': 'zip code tabulation area:77001,77002,77003,77004,77005,77006,77007,77008,77009,77010,77011,77012,77013,77014,77015,77016,77017,77018,77019,77020,77021,77022,77023,77024,77025,77026,77027,77028,77029,77030,77031,77032,77033,77034,77035,77036,77037,77038,77039,77040,77041,77042,77043,77044,77045,77046,77047,77048,77049,77050,77051,77052,77054,77055,77056,77057,77058,77059,77060,77061,77062,77063,77064,77065,77066,77067,77068,77069,77070,77071,77072,77073,77074,77075,77076,77077,77078,77079,77080,77081,77082,77083,77084,77085,77086,77087,77088,77089,77090,77091,77092,77093,77094,77095,77096,77097,77098,77099,77201,77202,77203,77205,77206,77207,77208,77210,77212,77213,77215,77217,77218,77219,77220,77221,77222,77223,77224,77225,77226,77227,77228,77229,77230,77231,77233,77234,77235,77236,77237,77238,77240,77241,77242,77243,77244,77245,77248,77249,77251,77252,77253,77254,77255,77256,77257,77258,77259,77261,77262,77263,77265,77266,77267,77268,77269,77270,77271,77272,77273,77274,77275,77277,77279,77280,77281,77282,77284,77287,77288,77289,77290,77291,77292,77293,77315,77325,77336,77337,77338,77339,77345,77346,77347,77373,77375,77377,77379,77383,77388,77389,77391,77396,77401,77402,77410,77411,77413,77429,77433,77447,77449,77450,77484,77491,77492,77493,77501,77502,77503,77504,77505,77506,77507,77508,77520,77521,77522,77530,77532,77536,77547,77562,77571,77572,77586,77587,77598'})
census_workforce_2017 = pd.DataFrame(census_work_2017)
census_workforce_2017 = census_workforce_2017.rename(columns={"B23025_004E": "Total employed in civilian labor force",
                                                              "B08135_001E":"Aggregate travel time to work (in minutes)",
                                                                        "NAME": "Name", "zip code tabulation area": "Zipcode"})

census_workforce_2017 = census_workforce_2017[["Zipcode",
                                               "Total employed in civilian labor force",
                                               "Aggregate travel time to work (in minutes)"]]

# Total employment in civil workforce and Total time travel to work for year 2016

census_work_2016 = c_value_cost_2016.acs5.get(("NAME","B23025_004E","B08135_001E"),
                                                    {'for': 'zip code tabulation area:77001,77002,77003,77004,77005,77006,77007,77008,77009,77010,77011,77012,77013,77014,77015,77016,77017,77018,77019,77020,77021,77022,77023,77024,77025,77026,77027,77028,77029,77030,77031,77032,77033,77034,77035,77036,77037,77038,77039,77040,77041,77042,77043,77044,77045,77046,77047,77048,77049,77050,77051,77052,77054,77055,77056,77057,77058,77059,77060,77061,77062,77063,77064,77065,77066,77067,77068,77069,77070,77071,77072,77073,77074,77075,77076,77077,77078,77079,77080,77081,77082,77083,77084,77085,77086,77087,77088,77089,77090,77091,77092,77093,77094,77095,77096,77097,77098,77099,77201,77202,77203,77205,77206,77207,77208,77210,77212,77213,77215,77217,77218,77219,77220,77221,77222,77223,77224,77225,77226,77227,77228,77229,77230,77231,77233,77234,77235,77236,77237,77238,77240,77241,77242,77243,77244,77245,77248,77249,77251,77252,77253,77254,77255,77256,77257,77258,77259,77261,77262,77263,77265,77266,77267,77268,77269,77270,77271,77272,77273,77274,77275,77277,77279,77280,77281,77282,77284,77287,77288,77289,77290,77291,77292,77293,77315,77325,77336,77337,77338,77339,77345,77346,77347,77373,77375,77377,77379,77383,77388,77389,77391,77396,77401,77402,77410,77411,77413,77429,77433,77447,77449,77450,77484,77491,77492,77493,77501,77502,77503,77504,77505,77506,77507,77508,77520,77521,77522,77530,77532,77536,77547,77562,77571,77572,77586,77587,77598'})
census_workforce_2016 = pd.DataFrame(census_work_2016)
census_workforce_2016 = census_workforce_2016.rename(columns={"B23025_004E": "Total employed in civilian labor force",
                                                              "B08135_001E":"Aggregate travel time to work (in minutes)",
                                                                        "NAME": "Name", "zip code tabulation area": "Zipcode"})

census_workforce_2016 = census_workforce_2016[["Zipcode",
                                               "Total employed in civilian labor force",
                                               "Aggregate travel time to work (in minutes)"]]

# Total employment in civil workforce and Total time travel to work for year 2015
census_work_2015 = c_value_cost_2015.acs5.get(("NAME","B23025_004E","B08135_001E"),
                                                    {'for': 'zip code tabulation area:77001,77002,77003,77004,77005,77006,77007,77008,77009,77010,77011,77012,77013,77014,77015,77016,77017,77018,77019,77020,77021,77022,77023,77024,77025,77026,77027,77028,77029,77030,77031,77032,77033,77034,77035,77036,77037,77038,77039,77040,77041,77042,77043,77044,77045,77046,77047,77048,77049,77050,77051,77052,77054,77055,77056,77057,77058,77059,77060,77061,77062,77063,77064,77065,77066,77067,77068,77069,77070,77071,77072,77073,77074,77075,77076,77077,77078,77079,77080,77081,77082,77083,77084,77085,77086,77087,77088,77089,77090,77091,77092,77093,77094,77095,77096,77097,77098,77099,77201,77202,77203,77205,77206,77207,77208,77210,77212,77213,77215,77217,77218,77219,77220,77221,77222,77223,77224,77225,77226,77227,77228,77229,77230,77231,77233,77234,77235,77236,77237,77238,77240,77241,77242,77243,77244,77245,77248,77249,77251,77252,77253,77254,77255,77256,77257,77258,77259,77261,77262,77263,77265,77266,77267,77268,77269,77270,77271,77272,77273,77274,77275,77277,77279,77280,77281,77282,77284,77287,77288,77289,77290,77291,77292,77293,77315,77325,77336,77337,77338,77339,77345,77346,77347,77373,77375,77377,77379,77383,77388,77389,77391,77396,77401,77402,77410,77411,77413,77429,77433,77447,77449,77450,77484,77491,77492,77493,77501,77502,77503,77504,77505,77506,77507,77508,77520,77521,77522,77530,77532,77536,77547,77562,77571,77572,77586,77587,77598'})
census_workforce_2015 = pd.DataFrame(census_work_2015)
census_workforce_2015 = census_workforce_2015.rename(columns={"B23025_004E": "Total employed in civilian labor force",
                                                              "B08135_001E":"Aggregate travel time to work (in minutes)",
                                                                        "NAME": "Name", "zip code tabulation area": "Zipcode"})

census_workforce_2015 = census_workforce_2015[["Zipcode",
                                               "Total employed in civilian labor force",
                                               "Aggregate travel time to work (in minutes)"]]

# Total employment in civil workforce and Total time travel to work for year 2014
census_work_2014 = c_value_cost_2014.acs5.get(("NAME","B23025_004E","B08135_001E"),
                                                    {'for': 'zip code tabulation area:77001,77002,77003,77004,77005,77006,77007,77008,77009,77010,77011,77012,77013,77014,77015,77016,77017,77018,77019,77020,77021,77022,77023,77024,77025,77026,77027,77028,77029,77030,77031,77032,77033,77034,77035,77036,77037,77038,77039,77040,77041,77042,77043,77044,77045,77046,77047,77048,77049,77050,77051,77052,77054,77055,77056,77057,77058,77059,77060,77061,77062,77063,77064,77065,77066,77067,77068,77069,77070,77071,77072,77073,77074,77075,77076,77077,77078,77079,77080,77081,77082,77083,77084,77085,77086,77087,77088,77089,77090,77091,77092,77093,77094,77095,77096,77097,77098,77099,77201,77202,77203,77205,77206,77207,77208,77210,77212,77213,77215,77217,77218,77219,77220,77221,77222,77223,77224,77225,77226,77227,77228,77229,77230,77231,77233,77234,77235,77236,77237,77238,77240,77241,77242,77243,77244,77245,77248,77249,77251,77252,77253,77254,77255,77256,77257,77258,77259,77261,77262,77263,77265,77266,77267,77268,77269,77270,77271,77272,77273,77274,77275,77277,77279,77280,77281,77282,77284,77287,77288,77289,77290,77291,77292,77293,77315,77325,77336,77337,77338,77339,77345,77346,77347,77373,77375,77377,77379,77383,77388,77389,77391,77396,77401,77402,77410,77411,77413,77429,77433,77447,77449,77450,77484,77491,77492,77493,77501,77502,77503,77504,77505,77506,77507,77508,77520,77521,77522,77530,77532,77536,77547,77562,77571,77572,77586,77587,77598'})
census_workforce_2014 = pd.DataFrame(census_work_2014)
census_workforce_2014 = census_workforce_2014.rename(columns={"B23025_004E": "Total employed in civilian labor force",
                                                              "B08135_001E":"Aggregate travel time to work (in minutes)",
                                                                        "NAME": "Name", "zip code tabulation area": "Zipcode"})

census_workforce_2014 = census_workforce_2014[["Zipcode",
                                               "Total employed in civilian labor force",
                                               "Aggregate travel time to work (in minutes)"]]

# Total employment in civil workforce and Total time travel to work for year 2013
census_work_2013 = c_value_cost_2013.acs5.get(("NAME","B23025_004E","B08135_001E"),
                                                    {'for': 'zip code tabulation area:77001,77002,77003,77004,77005,77006,77007,77008,77009,77010,77011,77012,77013,77014,77015,77016,77017,77018,77019,77020,77021,77022,77023,77024,77025,77026,77027,77028,77029,77030,77031,77032,77033,77034,77035,77036,77037,77038,77039,77040,77041,77042,77043,77044,77045,77046,77047,77048,77049,77050,77051,77052,77054,77055,77056,77057,77058,77059,77060,77061,77062,77063,77064,77065,77066,77067,77068,77069,77070,77071,77072,77073,77074,77075,77076,77077,77078,77079,77080,77081,77082,77083,77084,77085,77086,77087,77088,77089,77090,77091,77092,77093,77094,77095,77096,77097,77098,77099,77201,77202,77203,77205,77206,77207,77208,77210,77212,77213,77215,77217,77218,77219,77220,77221,77222,77223,77224,77225,77226,77227,77228,77229,77230,77231,77233,77234,77235,77236,77237,77238,77240,77241,77242,77243,77244,77245,77248,77249,77251,77252,77253,77254,77255,77256,77257,77258,77259,77261,77262,77263,77265,77266,77267,77268,77269,77270,77271,77272,77273,77274,77275,77277,77279,77280,77281,77282,77284,77287,77288,77289,77290,77291,77292,77293,77315,77325,77336,77337,77338,77339,77345,77346,77347,77373,77375,77377,77379,77383,77388,77389,77391,77396,77401,77402,77410,77411,77413,77429,77433,77447,77449,77450,77484,77491,77492,77493,77501,77502,77503,77504,77505,77506,77507,77508,77520,77521,77522,77530,77532,77536,77547,77562,77571,77572,77586,77587,77598'})
census_workforce_2013 = pd.DataFrame(census_work_2013)
census_workforce_2013 = census_workforce_2013.rename(columns={"B23025_004E": "Total employed in civilian labor force",
                                                              "B08135_001E":"Aggregate travel time to work (in minutes)",
                                                                        "NAME": "Name", "zip code tabulation area": "Zipcode"})

census_workforce_2013 = census_workforce_2013[["Zipcode",
                                               "Total employed in civilian labor force",
                                               "Aggregate travel time to work (in minutes)"]]

# Total employment in civil workforce and Total time travel to work for year 2012
census_work_2012 = c_value_cost_2012.acs5.get(("NAME","B23025_004E","B08135_001E"),
                                                    {'for': 'zip code tabulation area:77001,77002,77003,77004,77005,77006,77007,77008,77009,77010,77011,77012,77013,77014,77015,77016,77017,77018,77019,77020,77021,77022,77023,77024,77025,77026,77027,77028,77029,77030,77031,77032,77033,77034,77035,77036,77037,77038,77039,77040,77041,77042,77043,77044,77045,77046,77047,77048,77049,77050,77051,77052,77054,77055,77056,77057,77058,77059,77060,77061,77062,77063,77064,77065,77066,77067,77068,77069,77070,77071,77072,77073,77074,77075,77076,77077,77078,77079,77080,77081,77082,77083,77084,77085,77086,77087,77088,77089,77090,77091,77092,77093,77094,77095,77096,77097,77098,77099,77201,77202,77203,77205,77206,77207,77208,77210,77212,77213,77215,77217,77218,77219,77220,77221,77222,77223,77224,77225,77226,77227,77228,77229,77230,77231,77233,77234,77235,77236,77237,77238,77240,77241,77242,77243,77244,77245,77248,77249,77251,77252,77253,77254,77255,77256,77257,77258,77259,77261,77262,77263,77265,77266,77267,77268,77269,77270,77271,77272,77273,77274,77275,77277,77279,77280,77281,77282,77284,77287,77288,77289,77290,77291,77292,77293,77315,77325,77336,77337,77338,77339,77345,77346,77347,77373,77375,77377,77379,77383,77388,77389,77391,77396,77401,77402,77410,77411,77413,77429,77433,77447,77449,77450,77484,77491,77492,77493,77501,77502,77503,77504,77505,77506,77507,77508,77520,77521,77522,77530,77532,77536,77547,77562,77571,77572,77586,77587,77598'})
census_workforce_2012 = pd.DataFrame(census_work_2012)
census_workforce_2012 = census_workforce_2012.rename(columns={"B23025_004E": "Total employed in civilian labor force",
                                                              "B08135_001E":"Aggregate travel time to work (in minutes)",
                                                                        "NAME": "Name", "zip code tabulation area": "Zipcode"})

census_workforce_2012 = census_workforce_2012[["Zipcode",
                                               "Total employed in civilian labor force",
                                               "Aggregate travel time to work (in minutes)"]]

# Total employment in civil workforce and Total time travel to work for year 2011
census_work_2011 = c_value_cost_2011.acs5.get(("NAME","B23025_004E","B08135_001E"),
                                                    {'for': 'zip code tabulation area:77001,77002,77003,77004,77005,77006,77007,77008,77009,77010,77011,77012,77013,77014,77015,77016,77017,77018,77019,77020,77021,77022,77023,77024,77025,77026,77027,77028,77029,77030,77031,77032,77033,77034,77035,77036,77037,77038,77039,77040,77041,77042,77043,77044,77045,77046,77047,77048,77049,77050,77051,77052,77054,77055,77056,77057,77058,77059,77060,77061,77062,77063,77064,77065,77066,77067,77068,77069,77070,77071,77072,77073,77074,77075,77076,77077,77078,77079,77080,77081,77082,77083,77084,77085,77086,77087,77088,77089,77090,77091,77092,77093,77094,77095,77096,77097,77098,77099,77201,77202,77203,77205,77206,77207,77208,77210,77212,77213,77215,77217,77218,77219,77220,77221,77222,77223,77224,77225,77226,77227,77228,77229,77230,77231,77233,77234,77235,77236,77237,77238,77240,77241,77242,77243,77244,77245,77248,77249,77251,77252,77253,77254,77255,77256,77257,77258,77259,77261,77262,77263,77265,77266,77267,77268,77269,77270,77271,77272,77273,77274,77275,77277,77279,77280,77281,77282,77284,77287,77288,77289,77290,77291,77292,77293,77315,77325,77336,77337,77338,77339,77345,77346,77347,77373,77375,77377,77379,77383,77388,77389,77391,77396,77401,77402,77410,77411,77413,77429,77433,77447,77449,77450,77484,77491,77492,77493,77501,77502,77503,77504,77505,77506,77507,77508,77520,77521,77522,77530,77532,77536,77547,77562,77571,77572,77586,77587,77598'})
census_workforce_2011 = pd.DataFrame(census_work_2011)
census_workforce_2011 = census_workforce_2011.rename(columns={"B23025_004E": "Total employed in civilian labor force",
                                                              "B08135_001E":"Aggregate travel time to work (in minutes)",
                                                                        "NAME": "Name", "zip code tabulation area": "Zipcode"})

census_workforce_2011 = census_workforce_2011[["Zipcode",
                                               "Total employed in civilian labor force",
                                               "Aggregate travel time to work (in minutes)"]]

In [6]:
#### API request and save raw data to csv
# Median household income for year 2017
c_value_cost_2017 = Census(api_key_census, year=2017)
census_income_2017 = c_value_cost_2017.acs5.get(("NAME","B19013_001E","B25077_001E"),
                                                    {'for': 'zip code tabulation area:77001,77002,77003,77004,77005,77006,77007,77008,77009,77010,77011,77012,77013,77014,77015,77016,77017,77018,77019,77020,77021,77022,77023,77024,77025,77026,77027,77028,77029,77030,77031,77032,77033,77034,77035,77036,77037,77038,77039,77040,77041,77042,77043,77044,77045,77046,77047,77048,77049,77050,77051,77052,77054,77055,77056,77057,77058,77059,77060,77061,77062,77063,77064,77065,77066,77067,77068,77069,77070,77071,77072,77073,77074,77075,77076,77077,77078,77079,77080,77081,77082,77083,77084,77085,77086,77087,77088,77089,77090,77091,77092,77093,77094,77095,77096,77097,77098,77099,77201,77202,77203,77205,77206,77207,77208,77210,77212,77213,77215,77217,77218,77219,77220,77221,77222,77223,77224,77225,77226,77227,77228,77229,77230,77231,77233,77234,77235,77236,77237,77238,77240,77241,77242,77243,77244,77245,77248,77249,77251,77252,77253,77254,77255,77256,77257,77258,77259,77261,77262,77263,77265,77266,77267,77268,77269,77270,77271,77272,77273,77274,77275,77277,77279,77280,77281,77282,77284,77287,77288,77289,77290,77291,77292,77293,77315,77325,77336,77337,77338,77339,77345,77346,77347,77373,77375,77377,77379,77383,77388,77389,77391,77396,77401,77402,77410,77411,77413,77429,77433,77447,77449,77450,77484,77491,77492,77493,77501,77502,77503,77504,77505,77506,77507,77508,77520,77521,77522,77530,77532,77536,77547,77562,77571,77572,77586,77587,77598'})
census_income_2017 = pd.DataFrame(census_income_2017)
census_income_2017 = census_income_2017.rename(columns={"B25077_001E": "Median Value",
                                                                "B19013_001E": "Median Household Income",
                                                                "NAME": "Name", "zip code tabulation area": "Zipcode"})
census_income_2017 = census_income_2017[["Zipcode",
                                             "Median Household Income",
                                             "Median Value"]]
# Median household income for year 2016
c_value_cost_2016 = Census(api_key_census, year=2016)
census_income_2016 = c_value_cost_2016.acs5.get(("NAME","B19013_001E","B25077_001E"),
                                                    {'for': 'zip code tabulation area:77001,77002,77003,77004,77005,77006,77007,77008,77009,77010,77011,77012,77013,77014,77015,77016,77017,77018,77019,77020,77021,77022,77023,77024,77025,77026,77027,77028,77029,77030,77031,77032,77033,77034,77035,77036,77037,77038,77039,77040,77041,77042,77043,77044,77045,77046,77047,77048,77049,77050,77051,77052,77054,77055,77056,77057,77058,77059,77060,77061,77062,77063,77064,77065,77066,77067,77068,77069,77070,77071,77072,77073,77074,77075,77076,77077,77078,77079,77080,77081,77082,77083,77084,77085,77086,77087,77088,77089,77090,77091,77092,77093,77094,77095,77096,77097,77098,77099,77201,77202,77203,77205,77206,77207,77208,77210,77212,77213,77215,77217,77218,77219,77220,77221,77222,77223,77224,77225,77226,77227,77228,77229,77230,77231,77233,77234,77235,77236,77237,77238,77240,77241,77242,77243,77244,77245,77248,77249,77251,77252,77253,77254,77255,77256,77257,77258,77259,77261,77262,77263,77265,77266,77267,77268,77269,77270,77271,77272,77273,77274,77275,77277,77279,77280,77281,77282,77284,77287,77288,77289,77290,77291,77292,77293,77315,77325,77336,77337,77338,77339,77345,77346,77347,77373,77375,77377,77379,77383,77388,77389,77391,77396,77401,77402,77410,77411,77413,77429,77433,77447,77449,77450,77484,77491,77492,77493,77501,77502,77503,77504,77505,77506,77507,77508,77520,77521,77522,77530,77532,77536,77547,77562,77571,77572,77586,77587,77598'})
census_income_2016 = pd.DataFrame(census_income_2016)
census_income_2016 = census_income_2016.rename(columns={"B25077_001E": "Median Value",
                                                                "B19013_001E": "Median Household Income",
                                                                "NAME": "Name", "zip code tabulation area": "Zipcode"})
census_income_2016 = census_income_2016[["Zipcode",
                                             "Median Household Income",
                                             "Median Value"]]
# Median household income for year 2015
c_value_cost_2015 = Census(api_key_census, year=2015)
census_income_2015 = c_value_cost_2015.acs5.get(("NAME","B19013_001E","B25077_001E"),
                                                    {'for': 'zip code tabulation area:77001,77002,77003,77004,77005,77006,77007,77008,77009,77010,77011,77012,77013,77014,77015,77016,77017,77018,77019,77020,77021,77022,77023,77024,77025,77026,77027,77028,77029,77030,77031,77032,77033,77034,77035,77036,77037,77038,77039,77040,77041,77042,77043,77044,77045,77046,77047,77048,77049,77050,77051,77052,77054,77055,77056,77057,77058,77059,77060,77061,77062,77063,77064,77065,77066,77067,77068,77069,77070,77071,77072,77073,77074,77075,77076,77077,77078,77079,77080,77081,77082,77083,77084,77085,77086,77087,77088,77089,77090,77091,77092,77093,77094,77095,77096,77097,77098,77099,77201,77202,77203,77205,77206,77207,77208,77210,77212,77213,77215,77217,77218,77219,77220,77221,77222,77223,77224,77225,77226,77227,77228,77229,77230,77231,77233,77234,77235,77236,77237,77238,77240,77241,77242,77243,77244,77245,77248,77249,77251,77252,77253,77254,77255,77256,77257,77258,77259,77261,77262,77263,77265,77266,77267,77268,77269,77270,77271,77272,77273,77274,77275,77277,77279,77280,77281,77282,77284,77287,77288,77289,77290,77291,77292,77293,77315,77325,77336,77337,77338,77339,77345,77346,77347,77373,77375,77377,77379,77383,77388,77389,77391,77396,77401,77402,77410,77411,77413,77429,77433,77447,77449,77450,77484,77491,77492,77493,77501,77502,77503,77504,77505,77506,77507,77508,77520,77521,77522,77530,77532,77536,77547,77562,77571,77572,77586,77587,77598'})
census_income_2015 = pd.DataFrame(census_income_2015)
census_income_2015 = census_income_2015.rename(columns={"B25077_001E": "Median Value",
                                                                "B19013_001E": "Median Household Income",
                                                                "NAME": "Name", "zip code tabulation area": "Zipcode"})
census_income_2015 = census_income_2015[["Zipcode",
                                             "Median Household Income",
                                             "Median Value"]]
# Median household income for year 2014
c_value_cost_2014 = Census(api_key_census, year=2014)
census_income_2014 = c_value_cost_2014.acs5.get(("NAME","B19013_001E","B25077_001E"),
                                                    {'for': 'zip code tabulation area:77001,77002,77003,77004,77005,77006,77007,77008,77009,77010,77011,77012,77013,77014,77015,77016,77017,77018,77019,77020,77021,77022,77023,77024,77025,77026,77027,77028,77029,77030,77031,77032,77033,77034,77035,77036,77037,77038,77039,77040,77041,77042,77043,77044,77045,77046,77047,77048,77049,77050,77051,77052,77054,77055,77056,77057,77058,77059,77060,77061,77062,77063,77064,77065,77066,77067,77068,77069,77070,77071,77072,77073,77074,77075,77076,77077,77078,77079,77080,77081,77082,77083,77084,77085,77086,77087,77088,77089,77090,77091,77092,77093,77094,77095,77096,77097,77098,77099,77201,77202,77203,77205,77206,77207,77208,77210,77212,77213,77215,77217,77218,77219,77220,77221,77222,77223,77224,77225,77226,77227,77228,77229,77230,77231,77233,77234,77235,77236,77237,77238,77240,77241,77242,77243,77244,77245,77248,77249,77251,77252,77253,77254,77255,77256,77257,77258,77259,77261,77262,77263,77265,77266,77267,77268,77269,77270,77271,77272,77273,77274,77275,77277,77279,77280,77281,77282,77284,77287,77288,77289,77290,77291,77292,77293,77315,77325,77336,77337,77338,77339,77345,77346,77347,77373,77375,77377,77379,77383,77388,77389,77391,77396,77401,77402,77410,77411,77413,77429,77433,77447,77449,77450,77484,77491,77492,77493,77501,77502,77503,77504,77505,77506,77507,77508,77520,77521,77522,77530,77532,77536,77547,77562,77571,77572,77586,77587,77598'})
census_income_2014 = pd.DataFrame(census_income_2014)
census_income_2014 = census_income_2014.rename(columns={"B25077_001E": "Median Value",
                                                                "B19013_001E": "Median Household Income",
                                                                "NAME": "Name", "zip code tabulation area": "Zipcode"})
census_income_2014 = census_income_2014[["Zipcode",
                                             "Median Household Income",
                                             "Median Value"]]
# Median household income for year 2013
c_value_cost_2013 = Census(api_key_census, year=2013)
census_income_2013 = c_value_cost_2013.acs5.get(("NAME","B19013_001E","B25077_001E"),
                                                    {'for': 'zip code tabulation area:77001,77002,77003,77004,77005,77006,77007,77008,77009,77010,77011,77012,77013,77014,77015,77016,77017,77018,77019,77020,77021,77022,77023,77024,77025,77026,77027,77028,77029,77030,77031,77032,77033,77034,77035,77036,77037,77038,77039,77040,77041,77042,77043,77044,77045,77046,77047,77048,77049,77050,77051,77052,77054,77055,77056,77057,77058,77059,77060,77061,77062,77063,77064,77065,77066,77067,77068,77069,77070,77071,77072,77073,77074,77075,77076,77077,77078,77079,77080,77081,77082,77083,77084,77085,77086,77087,77088,77089,77090,77091,77092,77093,77094,77095,77096,77097,77098,77099,77201,77202,77203,77205,77206,77207,77208,77210,77212,77213,77215,77217,77218,77219,77220,77221,77222,77223,77224,77225,77226,77227,77228,77229,77230,77231,77233,77234,77235,77236,77237,77238,77240,77241,77242,77243,77244,77245,77248,77249,77251,77252,77253,77254,77255,77256,77257,77258,77259,77261,77262,77263,77265,77266,77267,77268,77269,77270,77271,77272,77273,77274,77275,77277,77279,77280,77281,77282,77284,77287,77288,77289,77290,77291,77292,77293,77315,77325,77336,77337,77338,77339,77345,77346,77347,77373,77375,77377,77379,77383,77388,77389,77391,77396,77401,77402,77410,77411,77413,77429,77433,77447,77449,77450,77484,77491,77492,77493,77501,77502,77503,77504,77505,77506,77507,77508,77520,77521,77522,77530,77532,77536,77547,77562,77571,77572,77586,77587,77598'})
census_income_2013 = pd.DataFrame(census_income_2013)
census_income_2013 = census_income_2013.rename(columns={"B25077_001E": "Median Value",
                                                                "B19013_001E": "Median Household Income",
                                                                "NAME": "Name", "zip code tabulation area": "Zipcode"})
census_income_2013 = census_income_2013[["Zipcode",
                                             "Median Household Income",
                                             "Median Value"]]
# Median household income for year 2012
c_value_cost_2012 = Census(api_key_census, year=2012)
census_income_2012 = c_value_cost_2012.acs5.get(("NAME","B19013_001E","B25077_001E"),
                                                    {'for': 'zip code tabulation area:77001,77002,77003,77004,77005,77006,77007,77008,77009,77010,77011,77012,77013,77014,77015,77016,77017,77018,77019,77020,77021,77022,77023,77024,77025,77026,77027,77028,77029,77030,77031,77032,77033,77034,77035,77036,77037,77038,77039,77040,77041,77042,77043,77044,77045,77046,77047,77048,77049,77050,77051,77052,77054,77055,77056,77057,77058,77059,77060,77061,77062,77063,77064,77065,77066,77067,77068,77069,77070,77071,77072,77073,77074,77075,77076,77077,77078,77079,77080,77081,77082,77083,77084,77085,77086,77087,77088,77089,77090,77091,77092,77093,77094,77095,77096,77097,77098,77099,77201,77202,77203,77205,77206,77207,77208,77210,77212,77213,77215,77217,77218,77219,77220,77221,77222,77223,77224,77225,77226,77227,77228,77229,77230,77231,77233,77234,77235,77236,77237,77238,77240,77241,77242,77243,77244,77245,77248,77249,77251,77252,77253,77254,77255,77256,77257,77258,77259,77261,77262,77263,77265,77266,77267,77268,77269,77270,77271,77272,77273,77274,77275,77277,77279,77280,77281,77282,77284,77287,77288,77289,77290,77291,77292,77293,77315,77325,77336,77337,77338,77339,77345,77346,77347,77373,77375,77377,77379,77383,77388,77389,77391,77396,77401,77402,77410,77411,77413,77429,77433,77447,77449,77450,77484,77491,77492,77493,77501,77502,77503,77504,77505,77506,77507,77508,77520,77521,77522,77530,77532,77536,77547,77562,77571,77572,77586,77587,77598'})
census_income_2012 = pd.DataFrame(census_income_2012)
census_income_2012 = census_income_2012.rename(columns={"B25077_001E": "Median Value",
                                                                "B19013_001E": "Median Household Income",
                                                                "NAME": "Name", "zip code tabulation area": "Zipcode"})
census_income_2012 = census_income_2012[["Zipcode",
                                             "Median Household Income",
                                             "Median Value"]]
# Median household income for year 2011
c_value_cost_2011 = Census(api_key_census, year=2011)
census_income_2011 = c_value_cost_2011.acs5.get(("NAME","B19013_001E","B25077_001E"),
                                                    {'for': 'zip code tabulation area:77001,77002,77003,77004,77005,77006,77007,77008,77009,77010,77011,77012,77013,77014,77015,77016,77017,77018,77019,77020,77021,77022,77023,77024,77025,77026,77027,77028,77029,77030,77031,77032,77033,77034,77035,77036,77037,77038,77039,77040,77041,77042,77043,77044,77045,77046,77047,77048,77049,77050,77051,77052,77054,77055,77056,77057,77058,77059,77060,77061,77062,77063,77064,77065,77066,77067,77068,77069,77070,77071,77072,77073,77074,77075,77076,77077,77078,77079,77080,77081,77082,77083,77084,77085,77086,77087,77088,77089,77090,77091,77092,77093,77094,77095,77096,77097,77098,77099,77201,77202,77203,77205,77206,77207,77208,77210,77212,77213,77215,77217,77218,77219,77220,77221,77222,77223,77224,77225,77226,77227,77228,77229,77230,77231,77233,77234,77235,77236,77237,77238,77240,77241,77242,77243,77244,77245,77248,77249,77251,77252,77253,77254,77255,77256,77257,77258,77259,77261,77262,77263,77265,77266,77267,77268,77269,77270,77271,77272,77273,77274,77275,77277,77279,77280,77281,77282,77284,77287,77288,77289,77290,77291,77292,77293,77315,77325,77336,77337,77338,77339,77345,77346,77347,77373,77375,77377,77379,77383,77388,77389,77391,77396,77401,77402,77410,77411,77413,77429,77433,77447,77449,77450,77484,77491,77492,77493,77501,77502,77503,77504,77505,77506,77507,77508,77520,77521,77522,77530,77532,77536,77547,77562,77571,77572,77586,77587,77598'})
census_income_2011 = pd.DataFrame(census_income_2011)
census_income_2011 = census_income_2011.rename(columns={"B25077_001E": "Median Value",
                                                                "B19013_001E": "Median Household Income",
                                                                "NAME": "Name", "zip code tabulation area": "Zipcode"})
census_income_2011 = census_income_2011[["Zipcode",
                                             "Median Household Income",
                                             "Median Value"]]

    Zipcode  Median Household Income  Median Value
0     77002                  66776.0      220400.0
1     77003                  35258.0      112500.0
2     77004                  34079.0      209000.0
3     77005                 147026.0      689600.0
4     77006                  62821.0      329500.0
..      ...                      ...           ...
128   77562                  52139.0       91500.0
129   77571                  69004.0      119700.0
130   77586                  85746.0      192100.0
131   77587                  37147.0       87400.0
132   77598                  45773.0      118200.0

[133 rows x 3 columns]

In [8]:
#### API request for population and save raw data to csv
#### API request for population year 2017
pop = Census(api_key_census, year=2017)
pop_data = pop.acs5.get(("NAME", "B01003_001E"), {'for': 'zip code tabulation area:77001,77002,77003,77004,77005,77006,77007,77008,77009,77010,77011,77012,77013,77014,77015,77016,77017,77018,77019,77020,77021,77022,77023,77024,77025,77026,77027,77028,77029,77030,77031,77032,77033,77034,77035,77036,77037,77038,77039,77040,77041,77042,77043,77044,77045,77046,77047,77048,77049,77050,77051,77052,77054,77055,77056,77057,77058,77059,77060,77061,77062,77063,77064,77065,77066,77067,77068,77069,77070,77071,77072,77073,77074,77075,77076,77077,77078,77079,77080,77081,77082,77083,77084,77085,77086,77087,77088,77089,77090,77091,77092,77093,77094,77095,77096,77097,77098,77099,77201,77202,77203,77205,77206,77207,77208,77210,77212,77213,77215,77217,77218,77219,77220,77221,77222,77223,77224,77225,77226,77227,77228,77229,77230,77231,77233,77234,77235,77236,77237,77238,77240,77241,77242,77243,77244,77245,77248,77249,77251,77252,77253,77254,77255,77256,77257,77258,77259,77261,77262,77263,77265,77266,77267,77268,77269,77270,77271,77272,77273,77274,77275,77277,77279,77280,77281,77282,77284,77287,77288,77289,77290,77291,77292,77293,77315,77325,77336,77337,77338,77339,77345,77346,77347,77373,77375,77377,77379,77383,77388,77389,77391,77396,77401,77402,77410,77411,77413,77429,77433,77447,77449,77450,77484,77491,77492,77493,77501,77502,77503,77504,77505,77506,77507,77508,77520,77521,77522,77530,77532,77536,77547,77562,77571,77572,77586,77587,77598'})
census_pd7 = pd.DataFrame(pop_data)
census_pd7 = census_pd7.rename(columns={"B01003_001E": "2017",
                                      "NAME": "Name", "zip code tabulation area": "Zipcode"})
census_pd7 = census_pd7[["Zipcode","2017"]]

#### API request for population year 2016
c2016 = Census(api_key_census, year=2016)
census_data_2016 = c2016.acs5.get(("NAME", "B01003_001E"), {'for': 'zip code tabulation area:77001,77002,77003,77004,77005,77006,77007,77008,77009,77010,77011,77012,77013,77014,77015,77016,77017,77018,77019,77020,77021,77022,77023,77024,77025,77026,77027,77028,77029,77030,77031,77032,77033,77034,77035,77036,77037,77038,77039,77040,77041,77042,77043,77044,77045,77046,77047,77048,77049,77050,77051,77052,77054,77055,77056,77057,77058,77059,77060,77061,77062,77063,77064,77065,77066,77067,77068,77069,77070,77071,77072,77073,77074,77075,77076,77077,77078,77079,77080,77081,77082,77083,77084,77085,77086,77087,77088,77089,77090,77091,77092,77093,77094,77095,77096,77097,77098,77099,77201,77202,77203,77205,77206,77207,77208,77210,77212,77213,77215,77217,77218,77219,77220,77221,77222,77223,77224,77225,77226,77227,77228,77229,77230,77231,77233,77234,77235,77236,77237,77238,77240,77241,77242,77243,77244,77245,77248,77249,77251,77252,77253,77254,77255,77256,77257,77258,77259,77261,77262,77263,77265,77266,77267,77268,77269,77270,77271,77272,77273,77274,77275,77277,77279,77280,77281,77282,77284,77287,77288,77289,77290,77291,77292,77293,77315,77325,77336,77337,77338,77339,77345,77346,77347,77373,77375,77377,77379,77383,77388,77389,77391,77396,77401,77402,77410,77411,77413,77429,77433,77447,77449,77450,77484,77491,77492,77493,77501,77502,77503,77504,77505,77506,77507,77508,77520,77521,77522,77530,77532,77536,77547,77562,77571,77572,77586,77587,77598'})

census_pd6 = pd.DataFrame(census_data_2016)
census_pd6 = census_pd6.rename(columns={"B01003_001E": "2016",
                                      "NAME": "Name", "zip code tabulation area": "Zipcode"})
census_pd6 = census_pd6[["Zipcode","2016"]]

#### API request for population year 2015
c2015 = Census(api_key_census, year=2015)
census_data_2015 = c2015.acs5.get(("NAME", "B01003_001E"), {'for': 'zip code tabulation area:77001,77002,77003,77004,77005,77006,77007,77008,77009,77010,77011,77012,77013,77014,77015,77016,77017,77018,77019,77020,77021,77022,77023,77024,77025,77026,77027,77028,77029,77030,77031,77032,77033,77034,77035,77036,77037,77038,77039,77040,77041,77042,77043,77044,77045,77046,77047,77048,77049,77050,77051,77052,77054,77055,77056,77057,77058,77059,77060,77061,77062,77063,77064,77065,77066,77067,77068,77069,77070,77071,77072,77073,77074,77075,77076,77077,77078,77079,77080,77081,77082,77083,77084,77085,77086,77087,77088,77089,77090,77091,77092,77093,77094,77095,77096,77097,77098,77099,77201,77202,77203,77205,77206,77207,77208,77210,77212,77213,77215,77217,77218,77219,77220,77221,77222,77223,77224,77225,77226,77227,77228,77229,77230,77231,77233,77234,77235,77236,77237,77238,77240,77241,77242,77243,77244,77245,77248,77249,77251,77252,77253,77254,77255,77256,77257,77258,77259,77261,77262,77263,77265,77266,77267,77268,77269,77270,77271,77272,77273,77274,77275,77277,77279,77280,77281,77282,77284,77287,77288,77289,77290,77291,77292,77293,77315,77325,77336,77337,77338,77339,77345,77346,77347,77373,77375,77377,77379,77383,77388,77389,77391,77396,77401,77402,77410,77411,77413,77429,77433,77447,77449,77450,77484,77491,77492,77493,77501,77502,77503,77504,77505,77506,77507,77508,77520,77521,77522,77530,77532,77536,77547,77562,77571,77572,77586,77587,77598'})
census_pd5 = pd.DataFrame(census_data_2015)
census_pd5 = census_pd5.rename(columns={"B01003_001E": "2015",
                                        "NAME": "Name", "zip code tabulation area": "Zipcode"})

census_pd5 = census_pd5[["Zipcode","2015"]]

#### API request for population year 2014
c2014 = Census(api_key_census, year=2014)
census_data_2014 = c2014.acs5.get(("NAME", "B01003_001E"), {'for': 'zip code tabulation area:77001,77002,77003,77004,77005,77006,77007,77008,77009,77010,77011,77012,77013,77014,77015,77016,77017,77018,77019,77020,77021,77022,77023,77024,77025,77026,77027,77028,77029,77030,77031,77032,77033,77034,77035,77036,77037,77038,77039,77040,77041,77042,77043,77044,77045,77046,77047,77048,77049,77050,77051,77052,77054,77055,77056,77057,77058,77059,77060,77061,77062,77063,77064,77065,77066,77067,77068,77069,77070,77071,77072,77073,77074,77075,77076,77077,77078,77079,77080,77081,77082,77083,77084,77085,77086,77087,77088,77089,77090,77091,77092,77093,77094,77095,77096,77097,77098,77099,77201,77202,77203,77205,77206,77207,77208,77210,77212,77213,77215,77217,77218,77219,77220,77221,77222,77223,77224,77225,77226,77227,77228,77229,77230,77231,77233,77234,77235,77236,77237,77238,77240,77241,77242,77243,77244,77245,77248,77249,77251,77252,77253,77254,77255,77256,77257,77258,77259,77261,77262,77263,77265,77266,77267,77268,77269,77270,77271,77272,77273,77274,77275,77277,77279,77280,77281,77282,77284,77287,77288,77289,77290,77291,77292,77293,77315,77325,77336,77337,77338,77339,77345,77346,77347,77373,77375,77377,77379,77383,77388,77389,77391,77396,77401,77402,77410,77411,77413,77429,77433,77447,77449,77450,77484,77491,77492,77493,77501,77502,77503,77504,77505,77506,77507,77508,77520,77521,77522,77530,77532,77536,77547,77562,77571,77572,77586,77587,77598'})
census_pd4 = pd.DataFrame(census_data_2014)
census_pd4 = census_pd4.rename(columns={"B01003_001E": "2014",
                                      "NAME": "Name", "zip code tabulation area": "Zipcode"})
census_pd4 = census_pd4[["Zipcode","2014"]]

#### API request for population year 2013
c2013 = Census(api_key_census, year=2013)
census_data_2013 = c2013.acs5.get(("NAME", "B01003_001E"), {'for': 'zip code tabulation area:77001,77002,77003,77004,77005,77006,77007,77008,77009,77010,77011,77012,77013,77014,77015,77016,77017,77018,77019,77020,77021,77022,77023,77024,77025,77026,77027,77028,77029,77030,77031,77032,77033,77034,77035,77036,77037,77038,77039,77040,77041,77042,77043,77044,77045,77046,77047,77048,77049,77050,77051,77052,77054,77055,77056,77057,77058,77059,77060,77061,77062,77063,77064,77065,77066,77067,77068,77069,77070,77071,77072,77073,77074,77075,77076,77077,77078,77079,77080,77081,77082,77083,77084,77085,77086,77087,77088,77089,77090,77091,77092,77093,77094,77095,77096,77097,77098,77099,77201,77202,77203,77205,77206,77207,77208,77210,77212,77213,77215,77217,77218,77219,77220,77221,77222,77223,77224,77225,77226,77227,77228,77229,77230,77231,77233,77234,77235,77236,77237,77238,77240,77241,77242,77243,77244,77245,77248,77249,77251,77252,77253,77254,77255,77256,77257,77258,77259,77261,77262,77263,77265,77266,77267,77268,77269,77270,77271,77272,77273,77274,77275,77277,77279,77280,77281,77282,77284,77287,77288,77289,77290,77291,77292,77293,77315,77325,77336,77337,77338,77339,77345,77346,77347,77373,77375,77377,77379,77383,77388,77389,77391,77396,77401,77402,77410,77411,77413,77429,77433,77447,77449,77450,77484,77491,77492,77493,77501,77502,77503,77504,77505,77506,77507,77508,77520,77521,77522,77530,77532,77536,77547,77562,77571,77572,77586,77587,77598'})
census_pd3 = pd.DataFrame(census_data_2013)
census_pd3 = census_pd3.rename(columns={"B01003_001E": "2013",
                                      "NAME": "Name", "zip code tabulation area": "Zipcode"})
census_pd3 = census_pd3[["Zipcode","2013"]]

#### API request for population year 2012
c2012 = Census(api_key_census, year=2012)
census_data_2012 = c2012.acs5.get(("NAME", "B01003_001E"), {'for': 'zip code tabulation area:77001,77002,77003,77004,77005,77006,77007,77008,77009,77010,77011,77012,77013,77014,77015,77016,77017,77018,77019,77020,77021,77022,77023,77024,77025,77026,77027,77028,77029,77030,77031,77032,77033,77034,77035,77036,77037,77038,77039,77040,77041,77042,77043,77044,77045,77046,77047,77048,77049,77050,77051,77052,77054,77055,77056,77057,77058,77059,77060,77061,77062,77063,77064,77065,77066,77067,77068,77069,77070,77071,77072,77073,77074,77075,77076,77077,77078,77079,77080,77081,77082,77083,77084,77085,77086,77087,77088,77089,77090,77091,77092,77093,77094,77095,77096,77097,77098,77099,77201,77202,77203,77205,77206,77207,77208,77210,77212,77213,77215,77217,77218,77219,77220,77221,77222,77223,77224,77225,77226,77227,77228,77229,77230,77231,77233,77234,77235,77236,77237,77238,77240,77241,77242,77243,77244,77245,77248,77249,77251,77252,77253,77254,77255,77256,77257,77258,77259,77261,77262,77263,77265,77266,77267,77268,77269,77270,77271,77272,77273,77274,77275,77277,77279,77280,77281,77282,77284,77287,77288,77289,77290,77291,77292,77293,77315,77325,77336,77337,77338,77339,77345,77346,77347,77373,77375,77377,77379,77383,77388,77389,77391,77396,77401,77402,77410,77411,77413,77429,77433,77447,77449,77450,77484,77491,77492,77493,77501,77502,77503,77504,77505,77506,77507,77508,77520,77521,77522,77530,77532,77536,77547,77562,77571,77572,77586,77587,77598'})
census_pd2 = pd.DataFrame(census_data_2012)
census_pd2 = census_pd2.rename(columns={"B01003_001E": "2012",
                                      "NAME": "Name", "zip code tabulation area": "Zipcode"})
census_pd2 = census_pd2[["Zipcode","2012"]]

#### API request for population year 2011
c2011 = Census(api_key_census, year=2011)
census_data_2011 = c2011.acs5.get(("NAME", "B01003_001E"), {'for': 'zip code tabulation area:77001,77002,77003,77004,77005,77006,77007,77008,77009,77010,77011,77012,77013,77014,77015,77016,77017,77018,77019,77020,77021,77022,77023,77024,77025,77026,77027,77028,77029,77030,77031,77032,77033,77034,77035,77036,77037,77038,77039,77040,77041,77042,77043,77044,77045,77046,77047,77048,77049,77050,77051,77052,77054,77055,77056,77057,77058,77059,77060,77061,77062,77063,77064,77065,77066,77067,77068,77069,77070,77071,77072,77073,77074,77075,77076,77077,77078,77079,77080,77081,77082,77083,77084,77085,77086,77087,77088,77089,77090,77091,77092,77093,77094,77095,77096,77097,77098,77099,77201,77202,77203,77205,77206,77207,77208,77210,77212,77213,77215,77217,77218,77219,77220,77221,77222,77223,77224,77225,77226,77227,77228,77229,77230,77231,77233,77234,77235,77236,77237,77238,77240,77241,77242,77243,77244,77245,77248,77249,77251,77252,77253,77254,77255,77256,77257,77258,77259,77261,77262,77263,77265,77266,77267,77268,77269,77270,77271,77272,77273,77274,77275,77277,77279,77280,77281,77282,77284,77287,77288,77289,77290,77291,77292,77293,77315,77325,77336,77337,77338,77339,77345,77346,77347,77373,77375,77377,77379,77383,77388,77389,77391,77396,77401,77402,77410,77411,77413,77429,77433,77447,77449,77450,77484,77491,77492,77493,77501,77502,77503,77504,77505,77506,77507,77508,77520,77521,77522,77530,77532,77536,77547,77562,77571,77572,77586,77587,77598'})
census_pd1 = pd.DataFrame(census_data_2011)
census_pd1 = census_pd1.rename(columns={"B01003_001E": "2011",
                                      "NAME": "Name", "zip code tabulation area": "Zipcode"})
census_pd1 = census_pd1[["Zipcode","2011"]]

In [9]:
#### Save raw data to csv
census_value_cost_2017.to_csv('HH_Value_And_Cost2017_Raw_NN.csv',index=False)
census_value_cost_2016.to_csv('HH_Value_And_Cost2016_Raw_NN.csv',index=False)
census_value_cost_2015.to_csv('HH_Value_And_Cost2015_Raw_NN.csv',index=False)
census_value_cost_2014.to_csv('HH_Value_And_Cost2014_Raw_NN.csv',index=False)
census_value_cost_2013.to_csv('HH_Value_And_Cost2013_Raw_NN.csv',index=False)
census_value_cost_2012.to_csv('HH_Value_And_Cost2012_Raw_NN.csv',index=False)
census_value_cost_2011.to_csv('HH_Value_And_Cost2011_Raw_NN.csv',index=False)

census_workforce_2017.to_csv('HH_Workforce2017_Raw_NN.csv',index=False)
census_workforce_2016.to_csv('HH_Workforce2016_Raw_NN.csv',index=False)
census_workforce_2016.to_csv('HH_Workforce2015_Raw_NN.csv',index=False)
census_workforce_2014.to_csv('HH_Workforce2014_Raw_NN.csv',index=False)
census_workforce_2013.to_csv('HH_Workforce2013_Raw_NN.csv',index=False)
census_workforce_2012.to_csv('HH_Workforce2012_Raw_NN.csv',index=False)
census_workforce_2011.to_csv('HH_Workforce2011_Raw_NN.csv',index=False)

census_income_2017.to_csv('HH_Income2017_Raw_NN.csv',index=False)
census_income_2016.to_csv('HH_Income2016_Raw_NN.csv',index=False)
census_income_2015.to_csv('HH_Income2015_Raw_NN.csv',index=False)
census_income_2014.to_csv('HH_Income2014_Raw_NN.csv',index=False)
census_income_2013.to_csv('HH_Income2013_Raw_NN.csv',index=False)
census_income_2012.to_csv('HH_Income2012_Raw_NN.csv',index=False)
census_income_2011.to_csv('HH_Income2011_Raw_NN.csv',index=False)

census_pd7.to_csv('HH_Pop2017_Raw_NN.csv',index=False)
census_pd6.to_csv('HH_Pop2016_Raw_NN.csv',index=False)
census_pd5.to_csv('HH_Pop2015_Raw_NN.csv',index=False)
census_pd4.to_csv('HH_Pop2014_Raw_NN.csv',index=False)
census_pd3.to_csv('HH_Pop2013_Raw_NN.csv',index=False)
census_pd2.to_csv('HH_Pop2012_Raw_NN.csv',index=False)
census_pd1.to_csv('HH_Pop2011_Raw_NN.csv',index=False)